-- myrmidon(M2-A): LLM gateway (LiteLLM) spend ledger and model catalog.
-- Generated by `pnpm --filter @paperclipai/db generate`; tag renamed to the
-- feature. Two new tables, additive only, no vendor table is touched:
--  - litellm_cost_events: gateway spend-log entries attributed to agents,
--    deduplicated by the gateway request_id (a regular unique index; rows
--    without a request_id never collide because the collector synthesizes a
--    deterministic id from agent and time).
--  - litellm_models: model catalog with the price rates /v1/model/info
--    last reported (insert-per-refresh keeps price history).
CREATE TABLE "litellm_cost_events" (
	"id" text PRIMARY KEY NOT NULL,
	"company_id" text NOT NULL,
	"agent_id" text NOT NULL,
	"issue_id" text,
	"heartbeat_run_id" text,
	"provider" text NOT NULL,
	"model" text NOT NULL,
	"input_tokens" integer DEFAULT 0 NOT NULL,
	"output_tokens" integer DEFAULT 0 NOT NULL,
	"cost_cents" integer NOT NULL,
	"occurred_at" timestamp with time zone NOT NULL,
	"request_id" text,
	"collected_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "litellm_models" (
	"id" text PRIMARY KEY NOT NULL,
	"model_name" text NOT NULL,
	"provider" text,
	"max_input_tokens" integer,
	"max_output_tokens" integer,
	"rates" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"seen_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "litellm_cost_events_request_uq" ON "litellm_cost_events" USING btree ("request_id");--> statement-breakpoint
CREATE INDEX "litellm_cost_events_company_occurred_idx" ON "litellm_cost_events" USING btree ("company_id","occurred_at");--> statement-breakpoint
CREATE INDEX "litellm_cost_events_company_run_idx" ON "litellm_cost_events" USING btree ("company_id","heartbeat_run_id");--> statement-breakpoint
CREATE UNIQUE INDEX "litellm_models_name_seen_uq" ON "litellm_models" USING btree ("model_name","seen_at");