import type { AdapterConfigSchema } from "@paperclipai/adapter-utils";
import { DEFAULT_EVENT_RECONNECT_MS, DEFAULT_TIMEOUT_SEC } from "../shared/constants.js";

export function getConfigSchema(): AdapterConfigSchema {
  return {
    fields: [
      {
        key: "apiBaseUrl",
        label: "API base URL",
        type: "text",
        required: true,
        hint: "Hermes API server base URL, such as http://127.0.0.1:8642 or a private HTTPS URL. The default dashboard root or chat URL, such as http://127.0.0.1:9119/chat, is accepted and maps to /api.",
      },
      {
        key: "apiKey",
        label: "API key",
        type: "text",
        required: true,
        hint: "Hermes API_SERVER_KEY, not PAPERCLIP_API_KEY. Stored as a Paperclip secret reference.",
        meta: { secret: true },
      },
      {
        // myrmidon(H3), release 1.1.2: the unsafe remote-HTTP toggle was
        // removed from the card schema. Plain http now requires a fleet
        // bot-container host name (myrmidon-bot-*, trusted by the adapter
        // itself); the dev-only escape hatch stays readable from raw
        // adapter config JSON (transport-security.ts) for local
        // development, but the card no longer advertises it and the bot
        // container sync (W2a) no longer writes it.
        key: "sessionKeyStrategy",
        label: "Session key strategy",
        type: "select",
        default: "issue",
        options: [
          { value: "issue", label: "Issue scoped" },
          { value: "agent", label: "Agent scoped" },
          { value: "run", label: "Run scoped" },
          { value: "none", label: "None" },
        ],
        hint: "Controls X-Hermes-Session-Key. Issue scoped prevents cross-task memory bleed by default.",
      },
      {
        key: "timeoutSec",
        label: "Timeout seconds",
        type: "number",
        default: DEFAULT_TIMEOUT_SEC,
      },
      {
        // myrmidon(G5): per-agent run-create timeout
        key: "createRequestTimeoutSec",
        label: "Run create timeout seconds",
        type: "number",
        hint: "How long POST /v1/runs may take to be accepted (5-300). Empty uses the instance default.",
      },
      {
        key: "eventReconnectMs",
        label: "Event reconnect ms",
        type: "number",
        default: DEFAULT_EVENT_RECONNECT_MS,
        hint: "Delay before reconnecting the Hermes SSE events stream after a nonterminal disconnect.",
      },
      {
        key: "paperclipApiUrl",
        label: "Paperclip API URL",
        type: "text",
        hint: "Optional Paperclip API URL reachable by the remote Hermes host. This is not a credential.",
      },
      {
        key: "headers",
        label: "Extra headers",
        type: "textarea",
        hint: "Optional JSON object of extra nonsecret headers. Security-critical headers are generated by the adapter.",
      },
      {
        key: "instructions",
        label: "Instructions",
        type: "textarea",
        hint: "Optional stable Hermes instructions sent separately from the wake input.",
      },
      // myrmidon(G4): expose the debugEvents escape hatch (gateway/index.ts's
      // agentConfigurationDoc, read by gateway/server/execute.ts) in the
      // schema so operators can find and toggle it without editing raw JSON,
      // same as the insecure-http toggle above.
      {
        key: "debugEvents",
        label: "Debug events (raw JSON logs)",
        type: "toggle",
        default: false,
        hint: "Log raw redacted Hermes gateway event JSON instead of the default compact hermes-chat-shaped progress lines. Verbose; for troubleshooting only.",
      },
    ],
  };
}
