export const INSECURE_REMOTE_HTTP_ESCAPE_HATCH = "dangerouslyAllowInsecureRemoteHttp";

// myrmidon(H3), release 1.1.2: the bot-container host prefix the adapter
// trusts for plain http. Bot containers live on the board's own docker
// network (MYRMIDON_BOT_NETWORK) and their Hermes API server has no
// certificate to offer, so the board-to-own-container hop is plain http by
// design; the container name is generated by the fleet's fixed template
// (containerNameFor: `myrmidon-bot-<botKey>`, botKey restricted to
// [a-z0-9-]), so this prefix cannot be squatted by an arbitrary hostname a
// card author types. Everything else — any other remote host — still needs
// HTTPS or the explicit dev escape hatch below.
export const BOT_CONTAINER_HOSTNAME_PREFIX = "myrmidon-bot-";

const BOT_CONTAINER_HOSTNAME_PATTERN = /^myrmidon-bot-[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/;

export function parseBooleanLike(value: unknown): boolean | null {
  if (typeof value === "boolean") return value;
  if (typeof value !== "string") return null;
  const normalized = value.trim().toLowerCase();
  if (["1", "true", "yes", "on"].includes(normalized)) return true;
  if (["0", "false", "no", "off"].includes(normalized)) return false;
  return null;
}

export function isLoopbackHostname(hostname: string): boolean {
  const value = hostname.toLowerCase().replace(/^\[|\]$/g, "");
  return (
    value === "localhost" ||
    value === "::1" ||
    value === "0:0:0:0:0:0:0:1" ||
    value === "127.0.0.1" ||
    /^127(?:\.\d{1,3}){3}$/.test(value)
  );
}

// myrmidon(H3): the fixed fleet template names bot containers
// `myrmidon-bot-<botKey>` with the same key charset the template validates
// (BOT_KEY_PATTERN), so a plain-http base URL to such a host is the
// board talking to its own container, not an unsafe remote.
export function isBotContainerHostname(hostname: string): boolean {
  return BOT_CONTAINER_HOSTNAME_PATTERN.test(hostname.toLowerCase().replace(/^\[|\]$/g, ""));
}

export function isRemotePlainHttp(url: URL): boolean {
  return url.protocol === "http:" && !isLoopbackHostname(url.hostname);
}

// myrmidon(H3): trust is now narrow — plain http is allowed without any
// card flag only for the fleet's own bot-container host names; the
// escape-hatch flag remains for unsafe local development against any other
// remote host and is no longer written into bot cards by the container
// sync (W2a used to set it because the adapter had no narrower way).
export function allowsInsecureRemoteHttp(url: URL, config: Record<string, unknown>): boolean {
  if (isBotContainerHostname(url.hostname)) return true;
  return parseBooleanLike(config[INSECURE_REMOTE_HTTP_ESCAPE_HATCH]) === true;
}

export function remotePlainHttpDeniedMessage(hostname: string): string {
  return (
    `Hermes gateway apiBaseUrl uses remote plain HTTP for "${hostname}". ` +
    `Use HTTPS or set ${INSECURE_REMOTE_HTTP_ESCAPE_HATCH}=true only for unsafe local development.`
  );
}
